on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - '[0-9]*.[0-9]*'

name: Create a release

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create a .tar.gz
        run: |
          set -xv
          t=${{ github.event.ref }}
          vsn=${t##*/}
          echo "vsn=$vsn" >> $GITHUB_ENV
          ./helpers/mk-versioned-archive --override-version=$vsn
          ./helpers/extract-top-changelog-entry > release-descr.txt
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.vsn }}
          name: Release ${{ env.vsn }}
          draft: false
          prerelease: false
          body_path: release-descr.txt
          files: gpb-${{ env.vsn }}.tar.gz
          fail_on_unmatched_files: true
